version: 2

references:
  workspace_root: &workspace_root /home/circleci/project

  node_image: &node_image circleci/node:8.10

  attach_workspace: &attach_workspace

  node_config: &node_config
    docker:
      - image: *node_image
    working_directory: *workspace_root

jobs:
  install:
    <<: *node_config
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - persist_to_workspace:
          root: *workspace_root
          paths:
            - .

  test-website:
    <<: *node_config
    steps:
      - attach_workspace:
          at: .

      - run: yarn lerna run --scope @thirteen/website --scope @thirteen/website-builder --scope @thirteen/api-static test

  deploy-website:
    <<: *node_config
    steps:
      - attach_workspace:
          at: .

      - run: yarn deploy:website

workflows:
  version: 2
  build-deploy:
    jobs:
      - install:
          filters:
            branches:
              ignore: gh-pages
      - test-website:
          requires:
            - install
      - deploy-website:
          requires:
            - install
            - test-website
      # - test-bot:
      #     requires:
      #       - install
      # - deploy-bot:
      #     requires:
      #       - install
      #       - test-website
      #       - test-bot
