AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Domain:
    Type: String
    Description: 'base domain, without any subdomain'
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
  SubDomain:
    Type: String
    Description: 'subdomain'
  githubAppId:
    Type: String
  githubAppPrivateKey:
    Type: String
  browserStackUser:
    Type: String
  browserStackKey:
    Type: String

Resources:
  githubWebhook:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt lambdaRole.Arn
      CodeUri: ./.build/bundle.zip
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          SUBMISSION_BUCKET_NAME: !Ref staticAssetBucket
          GITHUB_APP_ID: !Ref githubAppId
          GITHUB_APP_PRIVATE_KEY: !Ref githubAppPrivateKey
          BROWSER_STACK_USER: !Ref browserStackUser
          BROWSER_STACK_KEY: !Ref browserStackKey
          DEBUG: info
          APP_ORIGIN: !Sub 'http://${staticAssetBucket}.s3-website-${AWS::Region}.amazonaws.com'
      Events:
        webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST

  staticAssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${SubDomain}.${Domain}'
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

  lambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: allow-access-to-lambda-from-appsync
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:*'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - !Sub '${staticAssetBucket.Arn}'
                  - !Sub '${staticAssetBucket.Arn}/*'

Outputs:
  staticAssetBucket:
    Description: 'static asset bucket name'
    Value: !Ref staticAssetBucket

  s3Url:
    Description: 'bucket public access url'
    Value: !Sub 'https://${staticAssetBucket}.s3.${AWS::Region}.amazonaws.com'

  websiteUrl:
    Description: 'website url'
    Value: !Sub 'http://${staticAssetBucket}.s3-website-${AWS::Region}.amazonaws.com'
