export const event = {
  resource: '/webhook',
  path: '/webhook',
  httpMethod: 'POST',
  headers: {
    Accept: '*/*',
    'CloudFront-Forwarded-Proto': 'https',
    'CloudFront-Is-Desktop-Viewer': 'true',
    'CloudFront-Is-Mobile-Viewer': 'false',
    'CloudFront-Is-SmartTV-Viewer': 'false',
    'CloudFront-Is-Tablet-Viewer': 'false',
    'CloudFront-Viewer-Country': 'US',
    'content-type': 'application/json',
    Host: 'slo6hkmqo2.execute-api.eu-west-1.amazonaws.com',
    'User-Agent': 'GitHub-Hookshot/8d2b7f3',
    Via: '1.1 40c7f9ac0c01e97668f15d4b15f130a0.cloudfront.net (CloudFront)',
    'X-Amz-Cf-Id': '2tpKfGR4-uaHG6WmO7aXH20bo4K57G0JYk6VcGpmlsEA0JhqNwkQSw==',
    'X-Amzn-Trace-Id': 'Root=1-5bba928c-8d0e07e8aaf822341e325a98',
    'X-Forwarded-For': '192.30.252.39, 54.239.145.10',
    'X-Forwarded-Port': '443',
    'X-Forwarded-Proto': 'https',
    'X-GitHub-Delivery': '460262b0-ca86-11e8-9492-8cc6487cebd2',
    'X-GitHub-Event': 'pull_request',
  },
  multiValueHeaders: {
    Accept: ['*/*'],
    'CloudFront-Forwarded-Proto': ['https'],
    'CloudFront-Is-Desktop-Viewer': ['true'],
    'CloudFront-Is-Mobile-Viewer': ['false'],
    'CloudFront-Is-SmartTV-Viewer': ['false'],
    'CloudFront-Is-Tablet-Viewer': ['false'],
    'CloudFront-Viewer-Country': ['US'],
    'content-type': ['application/json'],
    Host: ['slo6hkmqo2.execute-api.eu-west-1.amazonaws.com'],
    'User-Agent': ['GitHub-Hookshot/8d2b7f3'],
    Via: ['1.1 40c7f9ac0c01e97668f15d4b15f130a0.cloudfront.net (CloudFront)'],
    'X-Amz-Cf-Id': ['2tpKfGR4-uaHG6WmO7aXH20bo4K57G0JYk6VcGpmlsEA0JhqNwkQSw=='],
    'X-Amzn-Trace-Id': ['Root=1-5bba928c-8d0e07e8aaf822341e325a98'],
    'X-Forwarded-For': ['192.30.252.39, 54.239.145.10'],
    'X-Forwarded-Port': ['443'],
    'X-Forwarded-Proto': ['https'],
    'X-GitHub-Delivery': ['460262b0-ca86-11e8-9492-8cc6487cebd2'],
    'X-GitHub-Event': ['pull_request'],
  },
  queryStringParameters: null,
  multiValueQueryStringParameters: null,
  pathParameters: null,
  stageVariables: null,
  requestContext: {
    resourceId: 'vhia9l',
    resourcePath: '/webhook',
    httpMethod: 'POST',
    extendedRequestId: 'OavWBFZqjoEFxPg=',
    requestTime: '07/Oct/2018:23:11:08 +0000',
    path: '/Prod/webhook',
    accountId: '741455069825',
    protocol: 'HTTP/1.1',
    stage: 'Prod',
    requestTimeEpoch: 1538953868938,
    requestId: '4657aea7-ca86-11e8-a111-8d747977d47d',
    identity: {
      cognitoIdentityPoolId: null,
      accountId: null,
      cognitoIdentityId: null,
      caller: null,
      sourceIp: '192.30.252.39',
      accessKey: null,
      cognitoAuthenticationType: null,
      cognitoAuthenticationProvider: null,
      userArn: null,
      userAgent: 'GitHub-Hookshot/8d2b7f3',
      user: null,
    },
    apiId: 'slo6hkmqo2',
  },
  isBase64Encoded: false,
  body: JSON.stringify({
    action: 'labeled',
    number: 4,
    pull_request: {
      url: 'https://api.github.com/repos/Platane/thirteen/pulls/4',
      id: 221965242,
      node_id: 'MDExOlB1bGxSZXF1ZXN0MjIxOTY1MjQy',
      html_url: 'https://github.com/Platane/thirteen/pull/4',
      diff_url: 'https://github.com/Platane/thirteen/pull/4.diff',
      patch_url: 'https://github.com/Platane/thirteen/pull/4.patch',
      issue_url: 'https://api.github.com/repos/Platane/thirteen/issues/4',
      number: 4,
      state: 'open',
      locked: false,
      title: 'sushi kitchen',
      user: {
        login: 'Platane',
        id: 1659820,
        node_id: 'MDQ6VXNlcjE2NTk4MjA=',
        avatar_url: 'https://avatars0.githubusercontent.com/u/1659820?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Platane',
        html_url: 'https://github.com/Platane',
        followers_url: 'https://api.github.com/users/Platane/followers',
        following_url:
          'https://api.github.com/users/Platane/following{/other_user}',
        gists_url: 'https://api.github.com/users/Platane/gists{/gist_id}',
        starred_url:
          'https://api.github.com/users/Platane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Platane/subscriptions',
        organizations_url: 'https://api.github.com/users/Platane/orgs',
        repos_url: 'https://api.github.com/users/Platane/repos',
        events_url: 'https://api.github.com/users/Platane/events{/privacy}',
        received_events_url:
          'https://api.github.com/users/Platane/received_events',
        type: 'User',
        site_admin: false,
      },
      body: '',
      created_at: '2018-10-10T23:39:05Z',
      updated_at: '2018-10-11T22:00:22Z',
      closed_at: null,
      merged_at: null,
      merge_commit_sha: '9e86c4243b14b9ab7498cee5730a85416302f763',
      assignee: null,
      assignees: [],
      requested_reviewers: [],
      requested_teams: [],
      labels: [[Object]],
      milestone: null,
      commits_url:
        'https://api.github.com/repos/Platane/thirteen/pulls/4/commits',
      review_comments_url:
        'https://api.github.com/repos/Platane/thirteen/pulls/4/comments',
      review_comment_url:
        'https://api.github.com/repos/Platane/thirteen/pulls/comments{/number}',
      comments_url:
        'https://api.github.com/repos/Platane/thirteen/issues/4/comments',
      statuses_url:
        'https://api.github.com/repos/Platane/thirteen/statuses/0f10f41250a949d3a596899e620fa553e8919cc3',
      head: {
        label: 'Platane:submission/sushi-kitchen',
        ref: 'submission/sushi-kitchen',
        sha: '0f10f41250a949d3a596899e620fa553e8919cc3',
        user: [Object],
        repo: [Object],
      },
      base: {
        label: 'Platane:master',
        ref: 'master',
        sha: 'f7fc31ee263b4004af0d092da6c9d5af5d68d7ce',
        user: [Object],
        repo: [Object],
      },
      _links: {
        self: [Object],
        html: [Object],
        issue: [Object],
        comments: [Object],
        review_comments: [Object],
        review_comment: [Object],
        commits: [Object],
        statuses: [Object],
      },
      author_association: 'OWNER',
      merged: false,
      mergeable: true,
      rebaseable: true,
      mergeable_state: 'clean',
      merged_by: null,
      comments: 0,
      review_comments: 0,
      maintainer_can_modify: false,
      commits: 2,
      additions: 14,
      deletions: 0,
      changed_files: 2,
    },
    label: {
      id: 1082630910,
      node_id: 'MDU6TGFiZWwxMDgyNjMwOTEw',
      url: 'https://api.github.com/repos/Platane/thirteen/labels/submission',
      name: 'submission',
      color: '166c84',
      default: false,
    },
    repository: {
      id: 151986185,
      node_id: 'MDEwOlJlcG9zaXRvcnkxNTE5ODYxODU=',
      name: 'thirteen',
      full_name: 'Platane/thirteen',
      private: false,
      owner: {
        login: 'Platane',
        id: 1659820,
        node_id: 'MDQ6VXNlcjE2NTk4MjA=',
        avatar_url: 'https://avatars0.githubusercontent.com/u/1659820?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/Platane',
        html_url: 'https://github.com/Platane',
        followers_url: 'https://api.github.com/users/Platane/followers',
        following_url:
          'https://api.github.com/users/Platane/following{/other_user}',
        gists_url: 'https://api.github.com/users/Platane/gists{/gist_id}',
        starred_url:
          'https://api.github.com/users/Platane/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/Platane/subscriptions',
        organizations_url: 'https://api.github.com/users/Platane/orgs',
        repos_url: 'https://api.github.com/users/Platane/repos',
        events_url: 'https://api.github.com/users/Platane/events{/privacy}',
        received_events_url:
          'https://api.github.com/users/Platane/received_events',
        type: 'User',
        site_admin: false,
      },
      html_url: 'https://github.com/Platane/thirteen',
      description: null,
      fork: false,
      url: 'https://api.github.com/repos/Platane/thirteen',
      forks_url: 'https://api.github.com/repos/Platane/thirteen/forks',
      keys_url: 'https://api.github.com/repos/Platane/thirteen/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/Platane/thirteen/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/Platane/thirteen/teams',
      hooks_url: 'https://api.github.com/repos/Platane/thirteen/hooks',
      issue_events_url:
        'https://api.github.com/repos/Platane/thirteen/issues/events{/number}',
      events_url: 'https://api.github.com/repos/Platane/thirteen/events',
      assignees_url:
        'https://api.github.com/repos/Platane/thirteen/assignees{/user}',
      branches_url:
        'https://api.github.com/repos/Platane/thirteen/branches{/branch}',
      tags_url: 'https://api.github.com/repos/Platane/thirteen/tags',
      blobs_url:
        'https://api.github.com/repos/Platane/thirteen/git/blobs{/sha}',
      git_tags_url:
        'https://api.github.com/repos/Platane/thirteen/git/tags{/sha}',
      git_refs_url:
        'https://api.github.com/repos/Platane/thirteen/git/refs{/sha}',
      trees_url:
        'https://api.github.com/repos/Platane/thirteen/git/trees{/sha}',
      statuses_url:
        'https://api.github.com/repos/Platane/thirteen/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/Platane/thirteen/languages',
      stargazers_url:
        'https://api.github.com/repos/Platane/thirteen/stargazers',
      contributors_url:
        'https://api.github.com/repos/Platane/thirteen/contributors',
      subscribers_url:
        'https://api.github.com/repos/Platane/thirteen/subscribers',
      subscription_url:
        'https://api.github.com/repos/Platane/thirteen/subscription',
      commits_url:
        'https://api.github.com/repos/Platane/thirteen/commits{/sha}',
      git_commits_url:
        'https://api.github.com/repos/Platane/thirteen/git/commits{/sha}',
      comments_url:
        'https://api.github.com/repos/Platane/thirteen/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/Platane/thirteen/issues/comments{/number}',
      contents_url:
        'https://api.github.com/repos/Platane/thirteen/contents/{+path}',
      compare_url:
        'https://api.github.com/repos/Platane/thirteen/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/Platane/thirteen/merges',
      archive_url:
        'https://api.github.com/repos/Platane/thirteen/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/Platane/thirteen/downloads',
      issues_url:
        'https://api.github.com/repos/Platane/thirteen/issues{/number}',
      pulls_url: 'https://api.github.com/repos/Platane/thirteen/pulls{/number}',
      milestones_url:
        'https://api.github.com/repos/Platane/thirteen/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/Platane/thirteen/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/Platane/thirteen/labels{/name}',
      releases_url:
        'https://api.github.com/repos/Platane/thirteen/releases{/id}',
      deployments_url:
        'https://api.github.com/repos/Platane/thirteen/deployments',
      created_at: '2018-10-07T21:17:09Z',
      updated_at: '2018-10-10T23:34:43Z',
      pushed_at: '2018-10-11T21:38:08Z',
      git_url: 'git://github.com/Platane/thirteen.git',
      ssh_url: 'git@github.com:Platane/thirteen.git',
      clone_url: 'https://github.com/Platane/thirteen.git',
      svn_url: 'https://github.com/Platane/thirteen',
      homepage: null,
      size: 68,
      stargazers_count: 0,
      watchers_count: 0,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      open_issues_count: 1,
      license: null,
      forks: 0,
      open_issues: 1,
      watchers: 0,
      default_branch: 'master',
    },
    sender: {
      login: 'Platane',
      id: 1659820,
      node_id: 'MDQ6VXNlcjE2NTk4MjA=',
      avatar_url: 'https://avatars0.githubusercontent.com/u/1659820?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/Platane',
      html_url: 'https://github.com/Platane',
      followers_url: 'https://api.github.com/users/Platane/followers',
      following_url:
        'https://api.github.com/users/Platane/following{/other_user}',
      gists_url: 'https://api.github.com/users/Platane/gists{/gist_id}',
      starred_url:
        'https://api.github.com/users/Platane/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/Platane/subscriptions',
      organizations_url: 'https://api.github.com/users/Platane/orgs',
      repos_url: 'https://api.github.com/users/Platane/repos',
      events_url: 'https://api.github.com/users/Platane/events{/privacy}',
      received_events_url:
        'https://api.github.com/users/Platane/received_events',
      type: 'User',
      site_admin: false,
    },
    installation: {
      id: 370763,
      node_id: 'MDIzOkludGVncmF0aW9uSW5zdGFsbGF0aW9uMzcwNzYz',
    },
  }),
}
