AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs8.10
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DEBUG: info

Resources:
  githubWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../bot/.build/bundle.zip
      Events:
        webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST

  graphql:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api/.build/bundle.zip
      Events:
        graphql:
          Type: Api
          Properties:
            Path: /graphql
            Method: POST
        graphiql:
          Type: Api
          Properties:
            Path: /graphiql
            Method: GET
