AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs8.10
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DEBUG: info

Resources:
  githubWebhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../bot/.build/bundle.zip
      Events:
        webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST

  graphql:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api-graphql/.build/bundle.zip
      Events:
        graphql:
          Type: Api
          Properties:
            Path: /graphql
            Method: POST
        graphqlOptions:
          Type: Api
          Properties:
            Path: /graphql
            Method: OPTIONS
        graphiql:
          Type: Api
          Properties:
            Path: /graphiql
            Method: GET

  staticAssetBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html

Outputs:
  graphqlEndpoint:
    Description: 'graphql endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/graphql'
  s3Url:
    Description: 'bucket public access url'
    Value: !Sub 'http://${staticAssetBucket}.s3-website-${AWS::Region}.amazonaws.com'
  bucketName:
    Description: 'static asset bucket name'
    Value: !Ref staticAssetBucket
