AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs8.10
    Timeout: 30
    MemorySize: 256
    Environment:
      Variables:
        DEBUG: info

Resources:
  lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../bot/.build/bundle.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
