// import '../service/manifestSchema/__tests__/validateManifestSchema.test'
// import './valid.test'
// import './valid-nested-bundle.test'
// import './mal-placed.test'
// import './no-manifest.test'
// import './malformed-manifest.test'
// import './missing-image.test'
// import './invalid-image.test'
// import './large-bundle.test'
// import './game-error.test'
// import './blank-game.test'
import './illegal-request.test'
