import '../service/manifestSchema/__tests__/validateManifestSchema.test'
import './valid.test'
import './missing-image.test'
import './game-error.test'
import './no-manifest.test'
import './mal-placed.test'
import './malformed-manifest.test'
